export const EDUCATIONAL_EMAILS = [
  {
    subject: "Guru Insight #1: The Nifty 50 Weightage Engine",
    title: "The Architecture of the Index",
    preview: "Reliance and HDFC Bank are the pulse of Nifty. Learn how they move the market.",
    body: "In the Indian market, Nifty is not just a number; it's a weighted average. To trade Nifty like a Guru, you must track the heavyweights. If Reliance and HDFC Bank are in sync, the index displaces with authority. Ignoring the weightage is trading with one eye closed.",
  },
  {
    subject: "Guru Insight #2: BankNifty Expiry Traps",
    title: "The Wednesday Zero-Hero Logic",
    preview: "Why 90% of retail traders lose their capital on Wednesday afternoons.",
    body: "BankNifty expiry is a harvest for institutions. They use 'Pinning' logic to keep price at specific strike prices where the maximum amount of options expire worthless. This is called 'Max Pain'. A Guru waits for the post-1:30 PM trend rather than gambling on the open.",
  },
  {
    subject: "Guru Insight #3: SGX/Gift Nifty Narrative",
    title: "The Pre-Market Global Compass",
    preview: "Understand the direction of the market before the 9:15 AM bell rings.",
    body: "The Gift Nifty (formerly SGX Nifty) gives us the institutional sentiment overnight. Gaps are common in the Indian market. A Guru doesn't chase the gap; they wait for the gap to be 'filled' or 'rejected' at an institutional order block.",
  },
  {
    subject: "Guru Insight #4: The 9:15 AM Opening Range",
    title: "Volatility vs. Value",
    preview: "The first 15 minutes set the tone for the entire session.",
    body: "The opening bell brings retail chaos. Institutions often sit back or execute 'Iceberg' orders during the first 15 minutes. We use the 'Opening Range' to identify if the day will be a 'Trend Day' or a 'Range Day'.",
  },
  {
    subject: "Guru Insight #5: FII & DII Data Logic",
    title: "Tracking the Giants",
    preview: "When Foreign Institutions sell, the market bleeds. When DIIs buy, it holds.",
    body: "The Indian market is a battle between Foreign Institutional Investors (FII) and Domestic Institutional Investors (DII). We track the Net-Net data every evening. If FIIs are heavy buyers in Cash, the institutional bias for the next day is overwhelmingly bullish.",
  },
  {
    subject: "Guru Insight #6: The Nifty Expiry (Thursday) Flush",
    title: "Liquidity Sweeps & Gamma Squeezes",
    preview: "Identifying the final trap before the weekly settlement.",
    body: "Thursday is the day of reckoning for weekly Nifty options. Institutions often sweep the previous day's high or low to trigger stop-losses before a massive reversal. This is the 'Gamma Squeeze' zone.",
  },
  {
    subject: "Guru Insight #7: The 1:30 PM European Impact",
    title: "Global Liquidity Synchronization",
    preview: "Why the Indian market often reverses when the European markets open.",
    body: "At 1:30 PM IST, European markets (FTSE, DAX) open. This brings a fresh wave of global liquidity into Indian equities. If Nifty has been trending all morning, watch for a 'Mean Reversion' or 'Distribution' when Europe enters.",
  },
  {
    subject: "Guru Insight #8: Option Chain 'Max Pain'",
    title: "The Institutional Magnet",
    preview: "Identify the strike price where institutions make the most profit.",
    body: "Max Pain is the strike price at which the total value of all outstanding call and put options is minimized. Price acts as a magnet to this level towards the end of the expiry. It is the footprint of the option writers—the true masters of the market.",
  },
  {
    subject: "Guru Insight #9: India VIX: The Fear Barometer",
    title: "Volatility & Option Pricing",
    preview: "If VIX is spiking, stop buying calls. Learn why.",
    body: "India VIX measures the expected volatility. When VIX rises, option premiums explode. A Guru knows that high VIX days require wider stop-losses and smaller position sizes. Lower VIX days are for precision momentum scalps.",
  },
  {
    subject: "Guru Insight #10: Nifty Round Number Psychology",
    title: "Institutional Order Blocks at 22,000/23,000",
    preview: "Round numbers are magnets for massive buy and sell orders.",
    body: "Psychological round numbers like 22,000 or 25,000 on Nifty are where institutions place their 'resting' orders. These levels act as massive Support or Resistance. A breakthrough with 'Displacement' at these levels signals a new macro trend.",
  },
  {
    subject: "Guru Insight #11: The FinNifty Tuesday Play",
    title: "Scalping the Financial Segment",
    preview: "Financial services have their own institutional rhythm on Tuesdays.",
    body: "FinNifty includes the giants of Indian finance. The Tuesday expiry often features high-speed mean reversions. We look for 'Sway' patterns where FinNifty deviates from Nifty to find high-probability entry points.",
  },
  {
    subject: "Guru Insight #12: Sector Rotation Elite",
    title: "Capital Flow: Bank vs. IT vs. Auto",
    preview: "Money never leaves the market; it just moves to a different sector.",
    body: "When BankNifty is exhausted, capital often flows into IT (TCS, Infosys) or Auto (Maruti). A Guru identifies which sector is leading the 'Charge' for the day and aligns their trades accordingly.",
  },
  {
    subject: "Guru Insight #13: FII Derivative Statistics",
    title: "Decoding the Index Long-Short Ratio",
    preview: "Are the big players shorting the index? Check the ratio.",
    body: "We look at the Index Future Long-Short ratio of FIIs. If they are 80% short, any minor rally will trigger a 'Short Covering Rally'. This is one of the most explosive moves in the Indian stock market.",
  },
  {
    subject: "Guru Insight #14: The Reliance Narrative",
    title: "The King of the Nifty 50",
    preview: "When Reliance moves 2%, Nifty has no choice but to follow.",
    body: "Reliance Industries is the single largest heavyweight. It sets the 'Daily Narrative'. If Reliance is trading above its previous day's high, the bias for Nifty is strictly 'Long' until the narrative shifts.",
  },
  {
    subject: "Guru Insight #15: SEBI Margin Impact",
    title: "Understanding Liquidity Constraints",
    preview: "How regulatory changes affect institutional and retail positioning.",
    body: "SEBI's margin rules have reduced the leverage available to retail. This has made the market less chaotic and more systemic. A Guru uses this to their advantage by trading institutional 'Order Flow' which is now clearer than ever.",
  },
  {
    subject: "Guru Insight #16: The 'Gap-Up' Rejection",
    title: "Trading the Institutional Sell-Off",
    preview: "Don't fall for the gap. Wait for the fill.",
    body: "Markets often gap up on news. Retail traders FOMO (Fear Of Missing Out) into the open. Institutions use this retail buying to 'Unload' their positions at a higher price. This often leads to a 'Gap Fill' by 11:00 AM.",
  },
  {
    subject: "Guru Insight #17: Midcap Select Volatility",
    title: "The Institutional Playground",
    preview: "High delta, high speed. Not for the faint of heart.",
    body: "Midcap Select is where the 'Smart Money' plays for high-alpha returns. The moves are fast and the spreads can be wide. Only trade Midcap if you have mastered the Nifty 50 precision logic.",
  },
  {
    subject: "Guru Insight #18: The 'Lunch Time' Trap",
    title: "Why 12:00 PM to 1:00 PM is a No-Trade Zone",
    preview: "Institutions are away. Retail is getting chopped.",
    body: "During the lunch hour in India, volume drops significantly. The market becomes a 'Zero Sum' game for retail traders. A Guru stays away from the terminal during this period to preserve capital for the PM session.",
  },
  {
    subject: "Guru Insight #19: HDFC Bank Institutional Levels",
    title: "The Heartbeat of BankNifty",
    preview: "Master HDFC Bank, and you master 30% of the BankNifty.",
    body: "HDFC Bank is the most tracked stock by institutions. We look for 'Fair Value Gaps' on the HDFC Bank 15m chart. When price returns to these gaps, BankNifty often finds its daily bottom or top.",
  },
  {
    subject: "Guru Insight #20: Nifty 'Flash' Movement",
    title: "Identifying Big Money Displacement",
    preview: "Spot the full-bodied candles that signal institutional entry.",
    body: "Institutional orders are massive. They create 'Displacement'—large, fast moves that leave gaps behind. If Nifty moves 50 points in 1 minute, that is an institutional footprint. Follow the displacement.",
  },
  {
    subject: "Guru Insight #21: The Power of 3 (PO3) in Nifty",
    title: "Accumulation, Manipulation, Distribution",
    preview: "The internal engine of a Nifty trend candle.",
    body: "Nifty often accumulates in the morning, manipulates with a fake move below the low, and then distributes in the main direction for the afternoon. Master the PO3 and you master the session.",
  },
  {
    subject: "Guru Insight #22: Option Chain PCR (Put-Call Ratio)",
    title: "The Sentiment Indicator",
    preview: "Is the market overbought or oversold? The PCR tells the truth.",
    body: "A PCR above 1.5 in Nifty often signals an 'Overbought' condition, while a PCR below 0.7 signals 'Oversold'. We look for PCR reversals at institutional support levels for high-probability counter-trend trades.",
  },
  {
    subject: "Guru Insight #23: The 'Daily Pivot' Strategy",
    title: "Precision Levels for Intraday Entry",
    preview: "Professional levels used by prop desks in Mumbai and Gurgaon.",
    body: "We use Central Pivot Range (CPR) and standard pivots to define the 'Battlefield'. If Nifty is trading above the CPR, the bias is 'Positive'. If it's caught inside, we wait for the expansion.",
  },
  {
    subject: "Guru Insight #24: Monthly Expiry Dynamics",
    title: "The Final Thursday of the Month",
    preview: "When long-term institutional contracts are rolled over.",
    body: "The monthly expiry is much more volatile than weekly. This is when institutions 'Roll Over' their positions to the next month. Watch for massive volatility spikes in the final 30 minutes of the market (3:00 PM - 3:30 PM).",
  },
  {
    subject: "Guru Insight #25: The Institutional 'Sweep' of Day Low",
    title: "Identifying the Liquidity Grab",
    preview: "Why Nifty often pokes below the morning low before a massive rally.",
    body: "Retail traders place their stops just below the morning low. Institutions push price down to 'Trigger' these stops, allowing them to buy at a lower price from the retail panicked selling.",
  },
  {
    subject: "Guru Insight #26: The Sensex & Nifty Correlation",
    title: "Tracking the Dual Indices",
    preview: "Do not ignore the BSE Sensex levels.",
    body: "While we trade Nifty, the Sensex is the broader market representation. If Sensex hits an all-time high but Nifty is lagging, there is 'Divergence'. This often leads to a fast 'Catch-Up' move in Nifty.",
  },
  {
    subject: "Guru Insight #27: Option Greek: Delta & Vega",
    title: "The Science of Premium Movement",
    preview: "Learn why your option doesn't move even when price does.",
    body: "A Guru understands Option Greeks. On expiry days, Gamma is king. On range-bound days, Theta (Time Decay) kills. We only take trades where the Greeks are in our favor for maximum 'Delta' expansion.",
  },
  {
    subject: "Guru Insight #28: ICICI Bank vs. HDFC Bank",
    title: "The Rivalry of the Financial Index",
    preview: "Which bank is leading the charge today?",
    body: "Often, one bank stays weak while the other is strong. This creates a range-bound BankNifty. We wait for 'Synchronization'—both banks moving in the same direction—for our most elite trades.",
  },
  {
    subject: "Guru Insight #29: High-Status Trading Discipline",
    title: "Operating like a Mumbai Prop Desk",
    preview: "Success is 20% strategy and 80% discipline.",
    body: "The best traders in India don't overtrade. They wait for their specific 'Setup'. They treat trading as a high-stakes business, not a casino. Elite status is earned through cold, calculated execution.",
  },
  {
    subject: "Guru Insight #30: The Eternal Indian Market Student",
    title: "The Final Lesson for the Guru",
    preview: "The journey from retail to institutional never ends.",
    body: "You have mastered the foundational Indian market insights. But the market is alive. It changes every day. Stay humble, keep backtesting Nifty/BankNifty, and maintain your elite Guru edges. The terminal is yours.",
  },
];
