import { ShieldCheck, TrendingUp, Calendar } from "lucide-react";

export default function PerformancePage() {
  return (
    <div className="bg-brand-surface min-h-screen py-32">
      <div className="container mx-auto px-4">
        <div className="text-center mb-20">
          <h1 className="text-brand-gold text-xs font-bold tracking-[0.4em] uppercase mb-4">AUDIT LOGS</h1>
          <h2 className="text-4xl md:text-6xl font-black text-brand-text uppercase tracking-tighter leading-tight">Institutional Accuracy.</h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-20">
           {[
             { month: "APRIL 2026", accuracy: "89.2%", trades: 42, yield: "+12.4%" },
             { month: "MARCH 2026", accuracy: "84.5%", trades: 38, yield: "+9.8%" },
             { month: "FEBRUARY 2026", accuracy: "87.1%", trades: 45, yield: "+11.2%" },
             { month: "JANUARY 2026", accuracy: "82.3%", trades: 34, yield: "+8.5%" },
           ].map((log, i) => (
             <div key={i} className="p-10 border border-brand-gold/10 bg-brand-surface-2 group">
                <div className="flex justify-between items-start mb-8">
                  <div className="space-y-1">
                    <span className="text-[10px] font-bold text-brand-gold tracking-[0.2em] uppercase">MONTHLY REPORT</span>
                    <h3 className="text-2xl font-black text-brand-text tracking-widest uppercase italic">{log.month}</h3>
                  </div>
                  <div className="px-4 py-2 bg-brand-gold text-black text-xs font-bold tracking-widest">VERIFIED</div>
                </div>
                <div className="grid grid-cols-3 gap-4 border-t border-brand-gold/10 pt-8">
                  <div className="text-center">
                    <p className="text-[10px] text-brand-gold-dark tracking-widest mb-2 font-bold">ACCURACY</p>
                    <p className="text-2xl font-bold text-brand-text">{log.accuracy}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] text-brand-gold-dark tracking-widest mb-2 font-bold">TRADES</p>
                    <p className="text-2xl font-bold text-brand-text">{log.trades}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] text-brand-gold-dark tracking-widest mb-2 font-bold">NET YIELD</p>
                    <p className="text-2xl font-bold text-green-500">{log.yield}</p>
                  </div>
                </div>
             </div>
           ))}
        </div>

        <div className="bg-brand-surface-2 p-12 border border-brand-gold/20 text-center">
          <p className="text-brand-gold-dark text-xs tracking-widest uppercase font-medium max-w-2xl mx-auto leading-loose">
            The Capital Guru maintains a 100% transparent execution log. Every trade signal generated by our institutional infrastructure is recorded and audited. Our goal is capital preservation through systemic precision.
          </p>
        </div>
      </div>
    </div>
  );
}
